import { cleanUsername } from './clean-username';

describe('cleanUsername', () => {
  it('should remove whitespace', () => {
    expect(cleanUsername('  ')).toEqual('');
  });

  it('should replace diacritics', () => {
    expect(cleanUsername('áàâäãéèëêíìïîóòöôõúùüûñçăşţ')).toEqual('aaaaaeeeeiiiiooooouuuuncast');
  });

  it('should remove characters that are not ascii, space, _ or -', () => {
    expect(cleanUsername('@]{^% ')).toEqual('');
  });

  it('should remove trailing whitespace', () => {
    expect(cleanUsername('abc   ')).toEqual('abc');
    expect(cleanUsername('   abc')).toEqual('abc');
  });

  it('should replace - by _', () => {
    expect(cleanUsername('a-b-c')).toEqual('a_b_c');
    expect(cleanUsername('-abc')).toEqual('_abc');
    expect(cleanUsername('abc-')).toEqual('abc_');
  });

  it('should replace spaces by _', () => {
    expect(cleanUsername('a b c')).toEqual('a_b_c');
  });

  it('should lowercase everything', () => {
    expect(cleanUsername('ABCdEfG')).toEqual('abcdefg');
  });

  it('should work with values generated by db triggers', () => {
    expect(cleanUsername('noir_direct_fuchsia_199723')).toEqual('noir_direct_fuchsia_199723');
  });
});
